spring.application.name=digital_bank
spring.datasource.url=jdbc:mysql://localhost:3306/bank 
spring.datasource.username=root
spring.datasource.password=@nkityadav06
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


app.jwt-secret=6bc9e70e253bcf5fa268b4cb73ac02604897a0008528229d3ac280dee5d023e5  
app.jwt-expiration-milliseconds=604800000